formatter: markdown

content: |-
{%- raw %}
    {{ .Header }}

    ## Usage

    Example:

    ```hcl
    {{ include "examples/main.tf" }}
    ```

    {{ .Footer }}

    {{ .Inputs }}

    {{ .Modules }}

    {{ .Outputs }}

    {{ .Providers }}

    {{ .Requirements }}

    {{ .Resources }}
{%- endraw %}

output:
  file: README.md
  mode: inject
  template: |-
{%- raw %}
    [//]: # (BEGIN_TF_DOCS)
    {{ .Content }}

    [//]: # (END_TF_DOCS)
{%- endraw %}
